# camera calibration matrix K
fx: 682.578
fy: 682.578
px: 482.0
py: 302.0

# rotation matrix R (in deg) (drone is assumed to be at 90° pitch, 90° roll)
yaw:   0
pitch: 90
roll:  -90

# vehicle coords of camera origin
XCam:  0
YCam:  0
ZCam: 50